export default [
  {
    id:1,
    type:'Soft drink',
    name:'Cocacola',
    image:'./asset/rekommendation/cocacola.jpg',
    cost:15,
  },
  {
    id:2,
    type:'Soft drink',
    name:'Crush orange',
    image:'./asset/rekommendation/crush_orange.jpeg',
    cost:20,
  },
  {
    id:3,
    type:'Soft drink',
    name:'Pepsi',
    image:'./asset/rekommendation/pepsi.png',
    cost:25,
  },
  {
    id:4,
    type:'Soft drink',
    name:'Sprite',
    image:'./asset/rekommendation/sprite.jpg',
    cost:15,
  },
  {
    id:5,
    type:'Soft drink',
    name:'Sprite',
    image:'./asset/rekommendation/sprite2.jpg',
    cost:20,
  },
  {
    id:6,
    type:'toppen',
    name:'Pommes',
    image:'./asset/rekommendation/pommes.jpg',
    cost:30,
  },  
  {
    id:8,
    type:'Soft drink',
    name:'Cocacola',
    image:'./asset/rekommendation/cocacola.jpg',
    cost:15,
  },
  {
    id:9,
    type:'Soft drink',
    name:'Crush orange',
    image:'./asset/rekommendation/crush_orange.jpeg',
    cost:20,
  },
  {
    id:10,
    type:'Soft drink',
    name:'Pepsi',
    image:'./asset/rekommendation/pepsi.png',
    cost:25,
  },
  {
    id:11,
    type:'Soft drink',
    name:'Sprite',
    image:'./asset/rekommendation/sprite.jpg',
    cost:15,
  },
  {
    id:12,
    type:'Soft drink',
    name:'sprite',
    image:'./asset/rekommendation/sprite2.jpg',
    cost:20,
  },
  {
    id:13,
    type:'toppen',
    name:'Pommes',
    image:'./asset/rekommendation/pommes.jpg',
    cost:30,
  }  
]